# Generated helper: declare every S4 generic exactly once, before any
# setClass/setMethod in the collated class files (this file sorts first).
#
# Rationale: the class files guard each generic with `if (!isGeneric("x"))`.
# That guard is defeated whenever a same-named generic already exists anywhere
# in the session (e.g. a previously loaded BulkSignalR, or stale S4 state left
# by a prior devtools::load_all()). When that happens the *local* generic is
# never created, and the subsequent setMethod() fails with
# "no existing definition for function '...'". Declaring the generics here,
# unconditionally and first, guarantees a package-local generic always exists.
# The existing guarded blocks then simply find it and skip, so no method
# definitions are ever wiped by a repeated setGeneric().

library(methods)

setGeneric("addClusterComp", function(obj, ...) standardGeneric("addClusterComp"))
setGeneric("addClusterCompPhos", function(obj, ...) standardGeneric("addClusterCompPhos"))
setGeneric("defineClusterComp", function(obj, ...) standardGeneric("defineClusterComp"))
setGeneric("getLRGeneSignatures", function(obj, ...) standardGeneric("getLRGeneSignatures"))
setGeneric("getPathwayStats", function(obj, ...) standardGeneric("getPathwayStats"))
setGeneric("initialInference", function(obj, ...) standardGeneric("initialInference"))
setGeneric("learnParameters", function(obj, ...) standardGeneric("learnParameters"))
setGeneric("reduceToBestPathway", function(obj, ...) standardGeneric("reduceToBestPathway"))
setGeneric("reduceToLigand", function(obj, ...) standardGeneric("reduceToLigand"))
setGeneric("reduceToPathway", function(obj, ...) standardGeneric("reduceToPathway"))
setGeneric("reduceToReceptor", function(obj, ...) standardGeneric("reduceToReceptor"))
setGeneric("removeClusterComp", function(obj, ...) standardGeneric("removeClusterComp"))
setGeneric("removeClusterCompPhos", function(obj, ...) standardGeneric("removeClusterCompPhos"))
setGeneric("rescoreInference", function(obj, ...) standardGeneric("rescoreInference"))
setGeneric("resetToInitialOrganism", function(obj, ...) standardGeneric("resetToInitialOrganism"))
setGeneric("scoreLRGeneSignatures", function(obj, ...) standardGeneric("scoreLRGeneSignatures"))
setGeneric("cmpName", function(x) standardGeneric("cmpName"))
setGeneric("colA", function(x) standardGeneric("colA"))
setGeneric("colB", function(x) standardGeneric("colB"))
setGeneric("comp", function(x) standardGeneric("comp"))
setGeneric("compPhos", function(x) standardGeneric("compPhos"))
setGeneric("dpg.corr", function(x) standardGeneric("dpg.corr"))
setGeneric("dp.genes", function(x) standardGeneric("dp.genes"))
setGeneric("dpg.logFC", function(x) standardGeneric("dpg.logFC"))
setGeneric("dpg.pval", function(x) standardGeneric("dpg.pval"))
setGeneric("infParam", function(x) standardGeneric("infParam"))
setGeneric("initialOrganism", function(x) standardGeneric("initialOrganism"))
setGeneric("initialOrthologs", function(x) standardGeneric("initialOrthologs"))
setGeneric("ligands", function(x) standardGeneric("ligands"))
setGeneric("logTransformed", function(x) standardGeneric("logTransformed"))
setGeneric("LRinter", function(x) standardGeneric("LRinter"))
setGeneric("ncounts", function(x) standardGeneric("ncounts"))
setGeneric("normalization", function(x) standardGeneric("normalization"))
setGeneric("param", function(x) standardGeneric("param"))
setGeneric("pathways", function(x) standardGeneric("pathways"))
setGeneric("pg.corr", function(x) standardGeneric("pg.corr"))
setGeneric("pgCorr", function(x) standardGeneric("pgCorr"))
setGeneric("p.genes", function(x) standardGeneric("p.genes"))
setGeneric("pGenes", function(x) standardGeneric("pGenes"))
setGeneric("pg.logFC", function(x) standardGeneric("pg.logFC"))
setGeneric("pg.pval", function(x) standardGeneric("pg.pval"))
setGeneric("phospho", function(x) standardGeneric("phospho"))
setGeneric("ptmg.corr", function(x) standardGeneric("ptmg.corr"))
setGeneric("ptm.genes", function(x) standardGeneric("ptm.genes"))
setGeneric("ptmg.logFC", function(x) standardGeneric("ptmg.logFC"))
setGeneric("ptmg.pval", function(x) standardGeneric("ptmg.pval"))
setGeneric("receptors", function(x) standardGeneric("receptors"))
setGeneric("single", function(x) standardGeneric("single"))
setGeneric("stats", function(x) standardGeneric("stats"))
setGeneric("statsPhospho", function(x) standardGeneric("statsPhospho"))
setGeneric("symPos", function(x) standardGeneric("symPos"))
setGeneric("tgCorr", function(x) standardGeneric("tgCorr"))
setGeneric("tGenes", function(x) standardGeneric("tGenes"))
setGeneric("tgLogFC", function(x) standardGeneric("tgLogFC"))
setGeneric("tgPval", function(x) standardGeneric("tgPval"))
setGeneric("cmpName<-", function(x,value) standardGeneric("cmpName<-"))
setGeneric("colA<-", function(x, value) standardGeneric("colA<-"))
setGeneric("colB<-", function(x, value) standardGeneric("colB<-"))
setGeneric("comp<-", function(x, value) standardGeneric("comp<-"))
setGeneric("compPhos<-", function(x, value) standardGeneric("compPhos<-"))
setGeneric("dpg.corr<-", function(x,value) standardGeneric("dpg.corr<-"))
setGeneric("dp.genes<-", function(x,value) standardGeneric("dp.genes<-"))
setGeneric("dpg.logFC<-", function(x,value) standardGeneric("dpg.logFC<-"))
setGeneric("dpg.pval<-", function(x,value) standardGeneric("dpg.pval<-"))
setGeneric("infParam<-", function(x,value) standardGeneric("infParam<-"))
setGeneric("ligands<-", function(x,value) standardGeneric("ligands<-"))
setGeneric("LRinter<-", function(x,value) standardGeneric("LRinter<-"))
setGeneric("ncounts<-", function(x, value) standardGeneric("ncounts<-"))
setGeneric("pg.corr<-", function(x,value) standardGeneric("pg.corr<-"))
setGeneric("pgCorr<-", function(x,value) standardGeneric("pgCorr<-"))
setGeneric("p.genes<-", function(x,value) standardGeneric("p.genes<-"))
setGeneric("pGenes<-", function(x,value) standardGeneric("pGenes<-"))
setGeneric("pg.logFC<-", function(x,value) standardGeneric("pg.logFC<-"))
setGeneric("pg.pval<-", function(x,value) standardGeneric("pg.pval<-"))
setGeneric("phospho<-", function(x, value) standardGeneric("phospho<-"))
setGeneric("ptmg.corr<-", function(x,value) standardGeneric("ptmg.corr<-"))
setGeneric("ptm.genes<-", function(x,value) standardGeneric("ptm.genes<-"))
setGeneric("ptmg.logFC<-", function(x,value) standardGeneric("ptmg.logFC<-"))
setGeneric("ptmg.pval<-", function(x,value) standardGeneric("ptmg.pval<-"))
setGeneric("receptors<-", function(x, value) standardGeneric("receptors<-"))
setGeneric("stats<-", function(x, value) standardGeneric("stats<-"))
setGeneric("statsPhospho<-", function(x, value) standardGeneric("statsPhospho<-"))
setGeneric("symPos<-", function(x, value) standardGeneric("symPos<-"))
setGeneric("tgCorr<-", function(x,value) standardGeneric("tgCorr<-"))
setGeneric("tGenes<-", function(x,value) standardGeneric("tGenes<-"))
setGeneric("tgLogFC<-", function(x,value) standardGeneric("tgLogFC<-"))
setGeneric("tgPval<-", function(x,value) standardGeneric("tgPval<-"))
